steps:

- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=secrets.txt.enc
  - --plaintext-file=secrets.txt
  - --location=global
  - --keyring=TestKeyRing
  - --key=TestKey
   
- name: 'gcr.io/concrete-crow-244606/sonar-scanner'
    args:
    - '-Dsonar.host.url=http://104.198.153.106:9000'
    - '-Dsonar.login=6368b35ae02c92d067fde1877f7b9f91941fe4d7'
    - '-Dsonar.projectKey=sample-project'
    - '-Dsonar.sources=.'
 
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/concrete-crow-244606/html-css-website-course', '.' ]

images:
- 'gcr.io/concrete-crow-244606/sonarqube'
- 'gcr.io/concrete-crow-244606/html-css-website-course'
