steps:
   
- name: 'gcr.io/concrete-crow-244606/sonar-scanner:latest'
    args:
    - '-Dsonar.host.url=http://35.238.221.161:9000'
    - '-Dsonar.login=c2a7631a6e402c338739091ffbc30e5e3d66cf19'
    - '-Dsonar.projectKey=sample-project'
    - '-Dsonar.sources=.'
 
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/concrete-crow-244606/html-css-website-course', '.' ]

images:
- 'gcr.io/concrete-crow-244606/html-css-website-course'
