steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=secrets.txt.enc
  - --plaintext-file=secrets.txt
  - --location=global
  - --keyring=TestKeyRing
  - --key=TestKey

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/chrome-empire-210218/html-css-website-course', '.' ]

images:
- 'gcr.io/chrome-empire-210218/html-css-website-course'
