steps:

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/chrome-empire-210218/html-css-website-course', '.' ] 
  args:
  - kms
  - decrypt
  - --ciphertext-file secrets.txt.encrypted
  - --plaintext-file secrets.txt.decrypted
  - --location=global
  - --keyring TestKeyRing
  - --key TestKey

secrets:
- kmsKeyName: projects/chrome-empire-210218/locations/global/keyRings/TestKeyRing/cryptoKeys/TestKey/cryptoKeyVersions/1

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/chrome-empire-210218/html-css-website-course'] 

images:
- 'gcr.io/chrome-empire-210218/html-css-website-course'
